# Generated by Django 3.2.6 on 2021-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=256, verbose_name='영상 제목')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
            ],
            options={
                'verbose_name': '세부 강의',
                'verbose_name_plural': '세부 강의',
                'db_table': 'detail_lecture_table',
            },
        ),
        migrations.CreateModel(
            name='FavouriteLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '즐겨찾기 강의',
                'verbose_name_plural': '즐겨찾기 강의',
                'db_table': 'favourite_lecture_table',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=256, verbose_name='강의 이름')),
                ('mentor_description', models.CharField(max_length=64, verbose_name='멘토 설명')),
                ('description', models.CharField(max_length=1000, verbose_name='설명')),
                ('price', models.CharField(max_length=64, verbose_name='가격')),
                ('field', models.CharField(blank=True, choices=[('A', '개발·프로그래밍'), ('B', '보안·네트워크'), ('C', '데이터 사이언스'), ('D', '크리에이티브'), ('E', '직무·마케팅'), ('F', '학문·외국어'), ('G', '커리어'), ('H', '교양')], max_length=64, null=True, verbose_name='분야')),
            ],
            options={
                'verbose_name': '전체 강의',
                'verbose_name_plural': '전체 강의',
                'db_table': 'lecture_table',
            },
        ),
        migrations.CreateModel(
            name='LectureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'My 강의',
                'verbose_name_plural': 'My 강의',
                'db_table': 'lecturelist_table',
            },
        ),
        migrations.CreateModel(
            name='Mentor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='멘토 이력')),
            ],
            options={
                'verbose_name': '멘토',
                'verbose_name_plural': '멘토',
                'db_table': 'mentor_table',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(blank=True, upload_to='', verbose_name='관련 이미지')),
            ],
            options={
                'verbose_name': '스펙',
                'verbose_name_plural': '스펙',
                'db_table': 'qualification_table',
            },
        ),
    ]
