# Generated by Django 3.2.6 on 2021-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        ('mentoringapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.user_info', verbose_name='유저 ID'),
        ),
        migrations.AddField(
            model_name='mentor_info',
            name='user_info_id',
            field=models.ForeignKey(db_column='user_info_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_info', verbose_name='멘토 이름'),
        ),
        migrations.AddField(
            model_name='lecturelist',
            name='lecture_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoringapp.lecture', verbose_name='강의 이름'),
        ),
        migrations.AddField(
            model_name='lecturelist',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.menti_info', verbose_name='신청한 사람'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='mentor_id',
            field=models.ForeignKey(db_column='mentor_id', on_delete=django.db.models.deletion.CASCADE, to='mentoringapp.mentor_info', verbose_name='멘토'),
        ),
        migrations.AddField(
            model_name='favouritelecture',
            name='lecture_title',
            field=models.ForeignKey(db_column='lecture_title', on_delete=django.db.models.deletion.CASCADE, to='mentoringapp.lecture', verbose_name='강의 이름'),
        ),
        migrations.AddField(
            model_name='favouritelecture',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='fav_user', to='myapp.menti_info', verbose_name='즐겨찾기한 사람'),
        ),
        migrations.AddField(
            model_name='detaillecture',
            name='lecture_title',
            field=models.ForeignKey(db_column='lecture_title', on_delete=django.db.models.deletion.CASCADE, to='mentoringapp.mentor_info', verbose_name='강의 이름'),
        ),
    ]
